version: '3.8'

services:
  cloudflare-ddns:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ZONE_ID=${ZONE_ID}
      - API_TOKEN=${API_TOKEN}
      - DOMAIN=${DOMAIN}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - TZ=${TZ:-Europe/Rome}
      - DOCKERIZED=TRUE
    volumes:
      - ./logs:/app/logs
    restart: always
